# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    name: "Update README.md"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          
      # Regenerate README.md
      - name: "Regenerate README.md"
        run: python3 $GITHUB_WORKSPACE/.github/scripts/readme.py
      
      - name: "Commit changes"
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          git config --global user.name 'Chinsyo'
          git config --global user.email 'chinsyo@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONSSECRET }}@github.com/$GITHUB_REPOSITORY
          git commit -am "Update README.md"
          git push
      
      

